version: "3.0"
services:
  wsclient:
    container_name: rust_client
    build: ./ws_client/
    depends_on:
      - wsserver
    volumes:
      - ./results-uwebsocket-cpp:/app/results
    tty: true
    cap_add:
      - NET_ADMIN
    deploy:
      resources:
        limits:
          cpus: '10'

  wsserver:
    container_name: uwcpp_server
    build: ./uws-server
    ports:
      - 3000:3000
    cap_add:
      - NET_ADMIN
    deploy:
      resources:
        limits:
          cpus: '1'

  # wsclient:
  #   container_name: go_client
  #   build: ./wsgo_client/
  #   depends_on:
  #     - wsserver
  #   # volumes:
  #   #   - ./ws_client/results-axum:/app/results
  #   tty: true
  #   cap_add:
  #     - NET_ADMIN
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '5'

  # wsserver:
  #   container_name: axum-server
  #   build: ./wsaxum
  #   cap_add:
  #     - NET_ADMIN
  #     - SYS_ADMIN
  #   privileged: true 
  #   ports:
  #     - 3000:3000
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '5'
