version: "3.0"
services:
  wsclient:
    container_name: rust_client
    build: ./clients/wsrust_client/
    depends_on:
      - wsserver
    volumes:
      - ./results/results-uwsjs:/app/results
    tty: true
    cap_add:
      - NET_ADMIN
    deploy:
      resources:
        limits:
          cpus: '10'

  wsserver:
    container_name: uwcpp_server
    build: ./servers/uwsjs-server
    ports:
      - 3000:3000
    cap_add:
      - NET_ADMIN
    deploy:
      resources:
        limits:
          cpus: '1'